### ISSUE TITLE
Issue with Load Categories in Activities

### ISSUE THREAD

**Issue by Iveth** [CustomerFX/FX.CustomLoader.Module#1]
Good Afternoon, I have a problem with a customization of activity, I try to replace the  Category picklist, and I need to hide this field and show the new Category Lookup.

When I use this instruction this.pk_Category.set('readonly', true); or this.pk_Category.set('visible', false); the aplication doesn't work, I use these instruction in the custom module.

This is the code:

define([
	'dojo/ready', 
	'dojo/_base/declare', 
	'dojo/aspect', 
	'dojo/_base/lang',
    'Sage/MainView/ActivityMgr/ActivityEditor', 
	'Sage/MainView/ActivityMgr/HistoryEditor', 
	'Sage/Services/ActivityService', 
	'Sage/UI/Controls/Lookup'
],
function (ready, declare, aspect, lang,
    ActivityEditor, HistoryEditor, ActivityService, Lookup) {

 
  function initializeActivityEditor() 
  {  
	
       this.pk_Category.set('visible', false);
            
  }
  initializeActivityEditor();
  //}
});

Please, I need your help.

Regards.

**Comment by CustomerFX** [comment]
Hello Iveth,

That falls outside the scope of this project. This project only loads the scripts. Try using the Infor forums for assistance with the script itself. 

Thanks.
